[build-system]
requires = ["setuptools"]

[project]
name = "cv-rendering"
version = "0.0.1"
dependencies = ["rendercv"]
requires-python = ">=3.10"
authors = [
  {name = "Francesco Andreuzzi", email = "andreuzzi.francesco@gmail.com"},
]

[tool.setuptools.packages.find]
include = ["cv_rendering*"]
